CREATE TABLE SALARIES (
ID NUMBER(8),
EMPLOYEE_ID NUMBER(10) NOT NULL,
PROJECT_ID NUMBER(10),
SALARY NUMBER(10,2) NOT NULL,
SALARIES_PK PRIMARY KEY(ID),
FK_SALARIES_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID),
FK_SALARIES_PROJECT FOREIGN KEY (PROJECT_ID) 
);
CREATE TABLE PROJECTS (
ID NUMBER(8),
CODE VARCHAR2(255) NOT NULL,
MANAGER_ID NUMBER(10),
BUDGET NUMBER(10,2) NOT NULL,
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE,
PROJECTS_PK PRIMARY KEY(ID),
FK_MANAGER_PROJECT FOREIGN KEY (MANAGER_ID)
);
CREATE TABLE EMPLOYEES (
ID NUMBER(8),
MANAGER_ID NUMBER(10),
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR2(255) NOT NULL,
EMPLOYEES_PK  PRIMARY KEY(ID),
FK_MANAGER FOREIGN KEY (MANAGER_ID)
)

SELECT COUNT(*)
  FROM PORJECTS
  WHERE  ID ='44905736599';
  
  


